application: multi-doc
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/bulkload
  script: admin_bulkload.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin
  
- url: .*
  script: main.py
  